version: '3.9'

services:

  backend:
    image:
      complaints.org/api
    ports:
      - "8080:8080"

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
     - type: tmpfs
       target: /dev/shm
       tmpfs:
         size: 134217728 
    environment:
      POSTGRES_PASSWORD: postdba 
    ports: 
      - "5433:5432"